# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test IP Pool
#
- hosts: localhost
  environment:
    PATH: "{{ ansible_env.PATH }}:/policy-ansible-for-nsxt"
  become: yes
  vars_files:
    - nsx_pacific_vars.yml
  tasks:
    - name: create IP Pool
      nsxt_ip_pool:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        state: "{{ state }}"
        pool_static_subnets: "{{ item.pool_static_subnets }}"
      with_items:
        - "{{ ip_pools }}"
