---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - nsx_pacific_vars.yml
  tasks:
    - name: Create Edge Transport Nodes
      nsxt_transport_nodes:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        host_switch_spec: "{{ item.host_switch_spec }}"
        node_deployment_info: "{{ item.node_deployment_info }}"
        state: "{{ state }}"
      with_items:
        - "{{ edge_transport_nodes }}"
