---
- hosts: localhost
  become: yes
  vars_files:
    - nsx_pacific_vars.yml
  tasks:
    - name: Sync Enforcement Point
      uri:
        url: "https://{{ nsx_node1.mgmt_ip }}/policy/api/v1/infra/sites/default/enforcement-points/default?action=reload"
        method: POST
        user: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        force_basic_auth: yes        
        
    - name: Create Tier0
      nsxt_tier0:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        state: "{{ state }}"
        display_name: "{{ item.display_name }}"
        ha_mode: "{{ item.ha_mode }}"
        locale_services: "{{ item.locale_services }}"
      with_items:
        - "{{ tier0_gateways }}"
