---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - nsx_pacific_vars.yml
  tasks:
    - name: Create Host Switch Profiles
      nsxt_uplink_profiles:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        resource_type: "{{ item.resource_type }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ item. transport_vlan }}"
        state: "{{ state }}"
      with_items:
        - "{{ host_switch_profiles }}"
