---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - nsx_pacific_vars.yml
  tasks:
    - name: Create Transport Node Profiles
      nsxt_transport_node_profiles:
        hostname: "{{ nsx_node1.mgmt_ip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        resource_type: "{{ item.resource_type }}"
        description: "{{ item.description }}"
        host_switch_spec: "{{ item.host_switch_spec }}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_node_profiles }}"
